config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :photos do
    put 'favourite', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  has_one_attached :image
  validate :image_presence
  validate :upload_is_image

  private

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def upload_is_image
    return unless image.attached?

    unless image.content_type =~ /^image\/(jpeg|pjpeg|gif|png|bmp)$/
      errors.add(:upload, 'not a valid image')
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Album not found.' }
      format.json { render json: e, status: :not_found }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_params
    params.require(:album).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :favourite]

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to album_path(@photo.album), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { redirect_to album_path(@photo.album), notice: @photo.errors.full_messages.join(', ') }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_back fallback_location: @photo.album, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: @photo.album, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favourite
    @photo.favourite = !@photo.favourite
    @photo.save

    respond_to do |format|
      format.html { render :show }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Photo not found.' }
      format.json { render json: e, status: :not_found }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:name, :description, :favourite, :album_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: '3' %>
  </div>


  <%= form.submit 'Save', class: 'btn btn-secondary btn-sm' %>
  <% if album.id %>
    <%= link_to 'View', album, class: 'btn btn-secondary btn-sm' %>
  <% end %>
  <%= link_to 'Back', albums_path, class: 'btn btn-secondary btn-sm' %>
<% end %>

app/views/albums/edit.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h1>Editing Album</h1>

    <%= render 'form', album: @album %>
  </div>
</div>

app/views/albums/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Albums</h1>
    <p class="lead text-muted">Find me in app/views/album/index.html.erb</p>
    <p>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">
        Add an album
      </button>
    </p>
  </div>
  <p id="notice"><%= notice %></p>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <% @albums.each do |album| %>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4">
            <% if album.photos.any? { |photo| photo.image.attached? }  %>
             <%#= image_tag album.photos.detect { |photo| photo.image.attached? }.image.variant(resize: "300x300"), class: 'mr-3'%>
             <%= image_tag album.photos.detect { |photo| photo.image.attached? }
                                .image.variant(combine_options: { resize: "x300", gravity: 'Center', crop: '300x300+0+0' }),
                                              class: 'img-thumbnail' %>
            <% else %>
              <img src="https://desarrollador-android.com/wp-content/uploads/2015/03/style_icons_system_grid_geometry2-300x300.png" class="img-thumbnail" alt="...">
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= album.name %></h5>
              <p class="card-text"><%= album.description %></p>
              <!-- TODO: helper needed -->
              <small class="text-muted"><%= album.photos.count %> Photo<%= 's' if (album.photos.count != 1) %></small>
              <div class="btn-group keypad">
                <%= link_to 'View', album, class: 'btn btn-secondary btn-sm' %>
                <%= link_to 'Edit', edit_album_path(album), class: 'btn btn-secondary btn-sm' %>
                <%= link_to 'Delete', album, method: :delete,
                                             data: { confirm: "#{'You will lost all photos in this Album. ' if album.photos.any?}\nAre you sure?" },
                                             class: 'btn btn-secondary btn-sm'  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Modal New Album -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add an album:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'albums/form', album: Album.new %>
      </div>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= @album.name %></h1>
    <p class="lead text-muted"><%= @album.description %></p>
    <p>
      <%= link_to 'Edit', edit_album_path(@album), class: 'btn btn-secondary btn-sm' %>
      <%= link_to 'Index', albums_path, class: 'btn btn-secondary btn-sm' %>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">
        Add a photo
      </button>
    </p>
  </div>
  <p id="notice"><%= notice %></p>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row no-gutters">
      <%= render @album.photos %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add a photo:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'photos/form', photo: @album.photos.build %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    <main role="main" style="min-height: 500px;">
      <%= yield %>
    </main>
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="{{ site.url }}/">Visit the homepage</a> or read our <a href="{{ site.baseurl }}/docs/{{ site.docs_version }}/getting-started/introduction/">getting started guide</a>.</p>
      </div>
    </footer>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <%= form.hidden_field :album_id %>
  <%= image_tag photo.image, class: 'img-fluid' if photo.image.attached? %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group form-check">
    <%= form.check_box :favourite, class: 'form-check-input' %>
    <%= form.label :favourite, class:'form-check-label' %>
  </div>
  <% unless photo.persisted? %>
    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  <% end %>
  <%= form.submit 'Save', class: 'btn btn-secondary btn-sm' %>
<% end %>

app/views/photos/_photo.html.erb
<% return unless photo.persisted? %>

<div class="col-md-6">
  <div class="card mb-6 shadow-sm">
    <%= image_tag photo.image.variant(combine_options: { resize: "x500", gravity: 'Center', crop: '500x500+0+0' }),
                                      class: 'img-thumbnail img-fluid' %>
    <div class="card-body">
      <h5 class="card-title"><%= photo.name %></h5>
      <p class="card-text"><%= photo.description %></p>
      <small class="text-muted">model: <%= photo.image.metadata['model'] %></small>
      <br>
      <small class="text-muted">exposure: <%= photo.image.metadata['exposure_time'] %></small>
      <br>
      <small class="text-muted">ISO speed: <%= photo.image.metadata['iso_speed_ratings'] %></small>
      <br>
      <small class="text-muted">focal length: <%= photo.image.metadata['focal_length'] %></small>
      <br>
      <small class="text-muted">date: <%= Date.parse(photo.image.metadata['date_time']) rescue nil %></small>
      <br>
      <div class="location">
        <small class="text-muted">location: <%= Location.new(photo.image.metadata['latitude'], photo.image.metadata['longitude']).location rescue '' %></small>
      </div>
      <!-- <small class="text-muted">exif <%== photo.image.metadata['exif'].try(:[], 0).inspect %></small> -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to 'Download', rails_blob_path(photo.image, disposition: "attachment"), class: 'btn btn-secondary btn-sm' %>
          <%#= link_to 'View', photo, class: 'btn btn-secondary btn-sm' %>
          <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#photo-edition-modal-<%= photo.id %>">
            Edit
          </button>
          <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary btn-sm'  %>
        </div>
        <!--  TODO: helper for buttons-->
        <span class='<%="fav_#{photo.id}"%>' >
          <%= link_to favourite_photo_path(photo), method: :put, remote: true, class: "btn #{ photo.favourite ? 'btn-warning' : 'btn-secondary'} btn-sm" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path d="M12 .288l2.833 8.718h9.167l-7.417 5.389 2.833 8.718-7.416-5.388-7.417 5.388 2.833-8.718-7.416-5.389h9.167z"/></svg>
          <% end %>
        <span>
      </div>
    </div>
  </div>
</div>
<!-- Modal Show Photo -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <img src="" class="imagepreview" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>
<!-- Modal Edit Photo -->
<div class="modal fade" id="photo-edition-modal-<%= photo.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= render 'photos/form', photo: photo %>
      </div>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/favourite.js.erb
$('.<%="fav_#{@photo.id}"%>').html(`<%= link_to favourite_photo_path(@photo), method: :put, remote: true, class: "btn #{ @photo.favourite ? 'btn-warning' : 'btn-secondary'} btn-sm" do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path d="M12 .288l2.833 8.718h9.167l-7.417 5.389 2.833 8.718-7.416-5.388-7.417 5.388 2.833-8.718-7.416-5.389h9.167z"/></svg>
<% end %>`)

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<p>
  <strong>Favourite:</strong>
  <%= @photo.favourite %>
</p>

<p>
  <strong>Album:</strong>
  <%= @photo.album %>
</p>

<p>exposure: <%= @photo.image.metadata['exif'].first['exposure_time'] %></p>
<p>ISO: <%= @photo.image.metadata['exif'].first['iso_speed_ratings'] %></p>
<p>focal_length: <%= @photo.image.metadata['exif'].first['focal_length'] %></p>

<%= image_tag Location.new(@photo.image.metadata['latitude'], @photo.image.metadata['longitude']).map_url, class: 'img-fluid' %>
<p><%= @photo.image.metadata['exif'].first.keys %></p>
<p><%= @photo.image.metadata %></p>

<%= image_tag @photo.image, class: 'img-fluid' if @photo.image.attached? %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>
<!-- TODO: Fav need a helper  -->
<%= link_to 'Fav', favourite_photo_path(@photo), method: :put, remote: false, class: "btn #{ @photo.favourite ? 'btn-warning' : 'btn-secondary'} btn-sm" %>